version: "3"

services:
  #
  # API
  #
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: 127.0.1.1
      DATABASE_NAME: "directusdb"
      DATABASE_USERNAME: "directusdb"
      DATABASE_PASSWORD: "directusdb"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directus"
    volumes:
      - ./volumes/uploads/:/var/www/html/public/uploads/
    ports:
      - 7000:80
    network_mode : "host"

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80